# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160224_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.Image'),
        ),
    ]
