# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160224_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
