# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_image_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='%Y/%m/%d', width_field='image_width'),
        ),
    ]
